### PR TITLE
Remove `future` (Drop py2 compatability), fixes DeprecatedWarning

### PR DESCRIPTION
**Pull request by kidmose**
Fixes richardpenman/pywhois#38 by removing `future` (Thereby dropping support for python 2)

Testing: I get two failues, just like master (`test_com_allsamples` and `test_dk_parse`) but the number of attributes that are wrong is (inadvertedly) decreased from 8/250 to 6/250 for `test_com_allsamples` and it is the same (1/9) for `test_dk_parse`.

### CODE REVIEW

**Comment by richardpenman** [comment]
is there an alternative way to support python 2 without the DeprecationWarning?

**Comment by kidmose** [comment]
I'm sure you can squelch the warning, and accept the use of a deprecated module. 
For my use, I went with our fork where this PR is merged, because it makes very good sense to me.
Hence, doing a PR for warning suppression is not a priority, sorry. 

Feel free to close this and #38 if you still are going for py2 support.

**Comment by toidi** [comment]
I agree py2 should be dropped.

Python2 users are still able to use older versions of the library.

**Comment by richardpenman** [comment]
closing since I want to keep Py2 compatibility while still possible

**Pull request closed without merging**
